name: Python Version

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  python-version:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: python/setup-python@v2
      with:
        python-version: '3.9'
    - name: Display Python version
      run: python --version
