name: Python Version

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  python-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python
        run: |
          sudo apt-get update && sudo apt-get install -y python3
      - name: Display Python version
        run: python3 --version
